fix: react hooks tag page
freeCodeCamp/ghost-config pull request #71
Opened 2021-10-25 02:34 UTC by scissorsneedfoodtoo

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)

Closes #XXXXX

Possible fix for the [React Hooks tag page](https://www.freecodecamp.org/news/tag/react-hooks/) that is currently redirected to https://www.freecodecamp.org/news/tag/why-react-hooks/.

2021-10-25 07:53 UTC, ojeytonwilliams requested changes

2021-11-12 07:24 UTC, scissorsneedfoodtoo commented on redirects.json
> +    "to": "^/why-react-hooks$",
Sorry @ojeytonwilliams, just seeing this now.

Thanks for the awesome suggestion, and for the reference. I was wondering why the redirect didn't work locally, then got distracted by other things.

This works great with my local Ghost installation.

2021-11-12 17:03 UTC, ojeytonwilliams approved these changes
LGTM :+1:

2022-01-24 20:03 UTC, nhcarrigan approved these changes
This fell off the radar but let's get this in. 🙂

2022-01-24 20:03 UTC, merged